export {
  USER_ROLE_ADMIN,
  USER_ROLE_AGENT,
  USER_ROLE_CLIENT,
  USER_ROLE_INSPECTOR,
  USER_ROLE_OWNER,
  USER_ROLE_TRANSACTION_MANAGER,
  USER_ROLE_VALUES,
  type UserRoleValue,
  ATTENDEE_ROLE_AGENT,
  ATTENDEE_ROLE_CLIENT,
} from '../../../shared/constants/roleConstants.js'
