import {
  API_STATUS_HIT,
  API_STATUS_ERROR,
  API_STATUS_NOT_CALLED,
  API_STATUS_COLOR_SUCCESS,
  API_STATUS_COLOR_ERROR,
  API_STATUS_COLOR_DEFAULT,
  API_STATUS_LABEL_HIT,
  API_STATUS_LABEL_ERROR,
  API_STATUS_LABEL_NOT_CALLED,
  type ApiStatusValue,
} from './apiStatusValues'

export const API_STATUS_COLOR_MAP: Record<ApiStatusValue, string> = {
  [API_STATUS_HIT]: API_STATUS_COLOR_SUCCESS,
  [API_STATUS_ERROR]: API_STATUS_COLOR_ERROR,
  [API_STATUS_NOT_CALLED]: API_STATUS_COLOR_DEFAULT,
}

export const API_STATUS_LABEL_MAP: Record<ApiStatusValue, string> = {
  [API_STATUS_HIT]: API_STATUS_LABEL_HIT,
  [API_STATUS_ERROR]: API_STATUS_LABEL_ERROR,
  [API_STATUS_NOT_CALLED]: API_STATUS_LABEL_NOT_CALLED,
}
