
export const APPOINTMENTS_TABLE_HEADERS = [
  { title: 'Property', key: 'propertyVersionId', sortable: true },
  { title: 'Property Type', key: 'propertyTypes', sortable: false },
  { title: 'Client', key: 'client', sortable: false },
  { title: 'Agent', key: 'agent', sortable: false },
  { title: 'Scheduled By', key: 'scheduledById', sortable: true },
  { title: 'Date', key: 'selectedDate', sortable: true },
  { title: 'Status', key: 'status', sortable: true },
  { title: 'Submitted', key: 'submittedAt', sortable: true },
  { title: 'Confirmed', key: 'confirmedAt', sortable: true },
  { title: 'Actions', key: 'actions', sortable: false },
] as const

export const APPOINTMENTS_TABLE_UI = {
  TITLE: 'Appointments',
  CREATE_BUTTON: 'Create Appointment',
  LOADING: 'Loading appointments...',
  ERROR_PREFIX: 'Error loading appointments:',
  EMPTY_MESSAGE: 'No appointments found. Click "Create Appointment" to add one.',
  CREATE_CARD_TITLE: 'Create New Appointment',
  PROPERTY_LABEL: 'Property *',
  CLIENT_LABEL: 'Client',
  AGENT_LABEL: 'Agent',
  SCHEDULED_BY_LABEL: 'Scheduled By',
  STATUS_LABEL: 'Status',
  QUOTE_MODE_LABEL: 'Quote Mode',
  SELECTED_DATE_LABEL: 'Selected Date',
  CANCEL: 'Cancel',
  SAVE: 'Save',
  DELETE_DIALOG_TITLE: 'Delete Appointment',
  DELETE_DIALOG_MESSAGE: 'Are you sure you want to delete this appointment? This action cannot be undone.',
  DELETE_DIALOG_CANCEL: 'Cancel',
  DELETE_DIALOG_CONFIRM: 'Delete',
  EDIT: 'Edit',
  DELETE: 'Delete',
  PROPERTY_TOOLTIP_TITLE: 'Property Details',
  CLIENT_TOOLTIP_TITLE: 'Client Details',
  AGENT_TOOLTIP_TITLE: 'Agent Details',
  NO_CLIENT: 'No client assigned',
  NO_AGENT: 'No agent assigned',
  NOT_SPECIFIED: 'Not specified',
  CLICK_PROPERTIES_TAB: 'Click to view in Properties tab',
  CLICK_USERS_TAB: 'Click to view in Users tab',
  ADDRESS: 'Address',
  UNIT: 'Unit',
  LOCATION: 'Location',
  SQ_FT: 'Sq Ft',
  BEDROOMS: 'Bedrooms',
  BATHROOMS: 'Bathrooms',
  FOUNDATION: 'Foundation',
  MLS: 'MLS #',
  PROPERTY_NOT_FOUND: 'Property not found',
  NAME: 'Name',
  EMAIL: 'Email',
  PHONE: 'Phone',
  ROLE: 'Role',
  OVERRIDE_CONSTRAINTS: 'Override',
  OVERRIDE_TOOLTIP: 'Override requires admin authentication (Feature 7)',
  CONFIRM: 'Confirm',
  CONFIRM_TOOLTIP: 'Confirm this submitted appointment',
  CONFIRM_DIALOG_TITLE: 'Confirm Appointment',
  CONFIRM_DIALOG_MESSAGE: 'Are you sure you want to confirm this appointment?',
  CONFIRM_SUCCESS: 'Appointment confirmed successfully',
  CONFIRM_ERROR: 'Failed to confirm appointment',
} as const
