
import {
  ENTITY_KEY_ANNOTATION_INSTANCE,
  ENTITY_KEY_ANNOTATION_SHAPE,
  ENTITY_KEY_BLOCK_INSTANCE,
  ENTITY_KEY_BLOCK_SHAPE,
  ENTITY_KEY_EVENT_INSTANCE,
  ENTITY_KEY_EVENT_SHAPE,
  ENTITY_KEY_PART_INSTANCE,
  ENTITY_KEY_PART_SHAPE,
} from './entitiesKeys'

export const ENTITY_KEYS = [
  ENTITY_KEY_BLOCK_INSTANCE,
  ENTITY_KEY_BLOCK_SHAPE,
  ENTITY_KEY_PART_INSTANCE,
  ENTITY_KEY_PART_SHAPE,
  ENTITY_KEY_EVENT_SHAPE,
  ENTITY_KEY_EVENT_INSTANCE,
  ENTITY_KEY_ANNOTATION_SHAPE,
  ENTITY_KEY_ANNOTATION_INSTANCE
] as const

export type GlobalEntityKey = (typeof ENTITY_KEYS)[number]

export type EntityMetadataType = GlobalEntityKey
