import type { Model, ModelCtor } from 'sequelize'

export type SequelizeModelsBag = {
  PartShape: ModelCtor<Model>
  PartInstance: ModelCtor<Model>
  BlockShape: ModelCtor<Model>
  BlockInstance: ModelCtor<Model>
  BlockInstanceVersion: ModelCtor<Model>
  PartInstanceVersion: ModelCtor<Model>
  ValidCascade: ModelCtor<Model>
  ValidPart: ModelCtor<Model>
  ValidAnnotation: ModelCtor<Model>
  ValidEvent: ModelCtor<Model>
  DependentInstance: ModelCtor<Model>
  BookingCascade: ModelCtor<Model>
  PricingCascade: ModelCtor<Model>
  ValidPricingCascade: ModelCtor<Model>
  PartAssignment: ModelCtor<Model>
  InstanceComponent: ModelCtor<Model>
  AnnotationShape: ModelCtor<Model>
  AnnotationInstance: ModelCtor<Model>
  AnnotationInstanceContent: ModelCtor<Model>
  AnnotationAssignment: ModelCtor<Model>
  EventShape: ModelCtor<Model>
  EventInstance: ModelCtor<Model>
  EventAssignment: ModelCtor<Model>
  EventShapeAttendee: ModelCtor<Model>
  AppointmentAttendee: ModelCtor<Model>
  Address: ModelCtor<Model>
  PropertyVersion: ModelCtor<Model>
  PropertyDetails: ModelCtor<Model>
  PropertyVersionType: ModelCtor<Model>
  User: ModelCtor<Model>
  Appointment: ModelCtor<Model>
  AppointmentSelectionLine: ModelCtor<Model>
  AppointmentTimeSlot: ModelCtor<Model>
  AppointmentFeeSummary: ModelCtor<Model>
  AppointmentFeeEntry: ModelCtor<Model>
  ConstraintOverride: ModelCtor<Model>
  CalendarSettings: ModelCtor<Model>
  WizardSettings: ModelCtor<Model>
  AvailabilitySetting: ModelCtor<Model>
  AvailabilityBusinessHour: ModelCtor<Model>
  AvailabilityBufferEntry: ModelCtor<Model>
  AvailabilityRangeConstraint: ModelCtor<Model>
  AvailabilityRangeConstraintHour: ModelCtor<Model>
  AvailabilityMaxWorkHour: ModelCtor<Model>
  AvailabilityMaxIncomeRow: ModelCtor<Model>
  AvailabilityDifferentialAttendee: ModelCtor<Model>
  CalendarSettingCalendar: ModelCtor<Model>
  BusinessRule: ModelCtor<Model>
  AdminMetadata: ModelCtor<Model>
  AdminMetadataSelectOption: ModelCtor<Model>
  AdminPrimitiveMetadata: ModelCtor<Model>
  AdminPrimitiveMetadataSelectOption: ModelCtor<Model>
  AdminRelationshipMetadata: ModelCtor<Model>
  AdminRelationshipMetadataSelectOption: ModelCtor<Model>
  BetaFeedback: ModelCtor<Model>
  BetaFeedbackTag: ModelCtor<Model>
  PropertyFieldMapping: ModelCtor<Model>
  PropertyFeatureMapping: ModelCtor<Model>
  Session: ModelCtor<Model>
  MagicLink: ModelCtor<Model>
}
