import { initializeModels } from "../db/models/index.js";
import { sequelize } from "./database.js";

export const {
  PartShape,
  PartInstance,
  BlockShape,
  BlockInstance,
  BlockInstanceVersion,
  PartInstanceVersion,
  ValidCascade,
  ValidPart,
  ValidAnnotation,
  ValidEvent,
  ValidPricingCascade,
  DependentInstance,
  BookingCascade,
  PricingCascade,
  PartAssignment,
  InstanceComponent,
  AnnotationShape,
  AnnotationInstance,
  AnnotationInstanceContent,
  AnnotationAssignment,
  EventShape,
  EventInstance,
  EventAssignment,
  EventShapeAttendee,
  Address,
  PropertyVersion,
  PropertyDetails,
  PropertyVersionType,
  User,
  Appointment,
  AppointmentSelectionLine,
  AppointmentAttendee,
  AppointmentFeeSummary,
  AppointmentFeeEntry,
  ConstraintOverride,
  BusinessSettings,
  CalendarSettings,
  WizardSettings,
  BusinessRule,
  AdminMetadata,
  AdminMetadataSelectOption,
  AdminPrimitiveMetadata,
  AdminPrimitiveMetadataSelectOption,
  AdminRelationshipMetadata,
  AdminRelationshipMetadataSelectOption,
  BetaFeedback,
  BetaFeedbackTag,
  PropertyFieldMapping,
  PropertyFeatureMapping,
} = initializeModels(sequelize);
