/**
 * LEARNING: Tabler Icons list for icon picker
 * 
 * WHY: Provides comprehensive list of Tabler icons for visual selection
 * 
 * PATTERN: Array of icon name strings (without 'tabler-' prefix in some cases, but we'll use full names)
 * 
 * NOTE: This is a curated list of commonly used Tabler icons. Can be expanded as needed.
 *       Full list available at https://tablericons.com/
 */

export const tablerIcons = [
  // Common UI icons
  'tabler-home',
  'tabler-user',
  'tabler-users',
  'tabler-settings',
  'tabler-menu-2',
  'tabler-x',
  'tabler-check',
  'tabler-plus',
  'tabler-minus',
  'tabler-edit',
  'tabler-trash',
  'tabler-search',
  'tabler-filter',
  'tabler-sort-ascending',
  'tabler-sort-descending',
  
  // Navigation
  'tabler-arrow-left',
  'tabler-arrow-right',
  'tabler-arrow-up',
  'tabler-arrow-down',
  'tabler-chevron-left',
  'tabler-chevron-right',
  'tabler-chevron-up',
  'tabler-chevron-down',
  'tabler-arrow-back',
  'tabler-arrow-forward',
  
  // Shopping & Commerce
  'tabler-shopping-cart',
  'tabler-shopping-bag',
  'tabler-credit-card',
  'tabler-currency-dollar',
  'tabler-receipt',
  'tabler-tag',
  'tabler-tags',
  
  // Communication
  'tabler-mail',
  'tabler-mail-opened',
  'tabler-phone',
  'tabler-message',
  'tabler-message-circle',
  'tabler-bell',
  'tabler-bell-ringing',
  
  // Files & Documents
  'tabler-file',
  'tabler-file-text',
  'tabler-file-upload',
  'tabler-file-download',
  'tabler-folder',
  'tabler-folder-open',
  'tabler-file-alert',
  'tabler-file-check',
  
  // Calendar & Time
  'tabler-calendar',
  'tabler-calendar-event',
  'tabler-clock',
  'tabler-hourglass',
  
  // Status & Feedback
  'tabler-alert-circle',
  'tabler-alert-triangle',
  'tabler-info-circle',
  'tabler-check-circle',
  'tabler-x-circle',
  'tabler-help-circle',
  
  // Media
  'tabler-photo',
  'tabler-camera',
  'tabler-video',
  'tabler-music',
  'tabler-play',
  'tabler-pause',
  
  // Business & Work
  'tabler-briefcase',
  'tabler-building',
  'tabler-building-store',
  'tabler-chart-bar',
  'tabler-chart-line',
  'tabler-chart-pie',
  'tabler-trending-up',
  'tabler-trending-down',
  
  // Location & Travel
  'tabler-map-pin',
  'tabler-map',
  'tabler-navigation',
  'tabler-plane',
  'tabler-car',
  'tabler-truck',
  
  // User Types (from migration)
  'tabler-clipboard-check', // Inspector
  // Note: tabler-shopping-cart, tabler-users, and tabler-home already listed above
  
  // Common Actions
  'tabler-download',
  'tabler-upload',
  'tabler-refresh',
  'tabler-reload',
  'tabler-save',
  'tabler-copy',
  'tabler-cut',
  'tabler-clipboard',
  'tabler-link',
  'tabler-external-link',
  
  // Layout & Design
  'tabler-layout',
  'tabler-layout-grid',
  'tabler-layout-list',
  'tabler-columns',
  'tabler-rows',
  'tabler-align-left',
  'tabler-align-center',
  'tabler-align-right',
  'tabler-align-justified',
  
  // Text Formatting
  'tabler-bold',
  'tabler-italic',
  'tabler-underline',
  'tabler-strikethrough',
  'tabler-typography',
  
  // Tools & Utilities
  'tabler-tool',
  'tabler-wrench',
  'tabler-screwdriver',
  'tabler-hammer',
  'tabler-paint',
  'tabler-color-picker',
  
  // Security & Privacy
  'tabler-lock',
  'tabler-lock-open',
  'tabler-shield',
  'tabler-shield-check',
  'tabler-key',
  'tabler-fingerprint',
  
  // Health & Medical
  'tabler-heart',
  'tabler-activity',
  'tabler-pulse',
  'tabler-stethoscope',
  'tabler-pill',
  
  // Education & Learning
  'tabler-school',
  'tabler-book',
  'tabler-bookmark',
  'tabler-certificate',
  'tabler-graduation-cap',
  
  // Technology
  'tabler-device-desktop',
  'tabler-device-mobile',
  'tabler-device-tablet',
  'tabler-wifi',
  'tabler-wifi-off',
  'tabler-bluetooth',
  'tabler-cpu',
  'tabler-server',
  
  // Weather & Nature
  'tabler-sun',
  'tabler-moon',
  'tabler-cloud',
  'tabler-cloud-rain',
  'tabler-snowflake',
  'tabler-leaf',
  'tabler-tree',
  
  // Food & Dining
  'tabler-coffee',
  'tabler-glass',
  'tabler-cake',
  'tabler-pizza',
  
  // Sports & Recreation
  'tabler-ball-football',
  'tabler-ball-basketball',
  'tabler-trophy',
  'tabler-medal',
  
  // Miscellaneous
  'tabler-star',
  'tabler-star-filled',
  'tabler-flag',
  'tabler-gift',
  'tabler-package',
  'tabler-box',
  'tabler-database',
  'tabler-server-2',
  'tabler-code',
  'tabler-bug',
  'tabler-lightbulb',
  'tabler-flame',
  'tabler-droplet',
  'tabler-circle',
  'tabler-circle-filled',
  'tabler-square',
  'tabler-square-filled',
  'tabler-triangle',
  'tabler-hexagon',
  
  // Additional common icons
  'tabler-eye',
  'tabler-eye-off',
  'tabler-eye-check',
  'tabler-zoom-in',
  'tabler-zoom-out',
  'tabler-maximize',
  'tabler-minimize',
  'tabler-arrows-maximize',
  'tabler-arrows-minimize',
  'tabler-resize',
  'tabler-move',
  'tabler-grip-vertical',
  'tabler-grip-horizontal',
  'tabler-dots',
  'tabler-dots-vertical',
  'tabler-dots-horizontal',
  'tabler-corner-down-left',
  'tabler-corner-down-right',
  'tabler-corner-up-left',
  'tabler-corner-up-right',
  'tabler-arrow-back-up',
  'tabler-arrow-forward-up',
  'tabler-arrow-up-circle',
  'tabler-arrow-left-circle',
  'tabler-arrow-right-circle',
  // Note: tabler-arrow-down-circle, tabler-chevron-up, and tabler-chevron-down already listed above
  'tabler-chevrons-left',
  'tabler-chevrons-right',
  'tabler-chevrons-up',
  'tabler-chevrons-down',
  'tabler-arrow-narrow-left',
  'tabler-arrow-narrow-right',
  'tabler-arrow-narrow-up',
  'tabler-arrow-narrow-down',
  'tabler-arrow-big-left',
  'tabler-arrow-big-right',
  'tabler-arrow-big-up',
  'tabler-arrow-big-down',
  'tabler-arrow-top-circle',
  'tabler-arrow-bottom-circle',
  'tabler-arrow-left-right',
  'tabler-arrow-up-down',
  'tabler-arrows-up',
  'tabler-arrows-down',
  'tabler-arrows-left',
  'tabler-arrows-right',
  'tabler-arrows-up-down',
  'tabler-arrows-left-right',
  'tabler-arrows-split',
  'tabler-arrows-join',
  'tabler-arrows-exchange',
  'tabler-arrows-shuffle',
  'tabler-arrows-random',
  'tabler-arrows-sort',
  'tabler-arrows-move',
  'tabler-arrows-move-vertical',
  'tabler-arrows-move-horizontal',
  'tabler-arrow-rotary-first-left',
  'tabler-arrow-rotary-last-left',
  'tabler-arrow-rotary-first-right',
  'tabler-arrow-rotary-last-right',
  'tabler-arrow-rotary-straight',
  'tabler-arrow-loop-left',
  'tabler-arrow-loop-right',
  'tabler-arrow-merge',
  'tabler-arrow-fork',
  'tabler-arrow-autofit-content',
  'tabler-arrow-autofit-down',
  'tabler-arrow-autofit-height',
  'tabler-arrow-autofit-left',
  'tabler-arrow-autofit-right',
  'tabler-arrow-autofit-up',
  'tabler-arrow-autofit-width',
  'tabler-arrow-bar-left',
  'tabler-arrow-bar-right',
  'tabler-arrow-bar-up',
  'tabler-arrow-bar-down',
  'tabler-arrow-bar-to-left',
  'tabler-arrow-bar-to-right',
  'tabler-arrow-bar-to-up',
  'tabler-arrow-bar-to-down',
  'tabler-arrow-bear-left',
  'tabler-arrow-bear-left-2',
  'tabler-arrow-bear-right',
  'tabler-arrow-bear-right-2',
  'tabler-arrow-big-down-line',
  'tabler-arrow-big-down-lines',
  'tabler-arrow-big-left-line',
  'tabler-arrow-big-left-lines',
  'tabler-arrow-big-right-line',
  'tabler-arrow-big-right-lines',
  'tabler-arrow-big-up-line',
  'tabler-arrow-big-up-lines',
  'tabler-arrow-bounce',
  'tabler-arrow-curve-left',
  'tabler-arrow-curve-right',
  'tabler-arrow-down-bar',
  // Note: tabler-arrow-down-circle already listed above
  'tabler-arrow-down-left',
  'tabler-arrow-down-left-circle',
  'tabler-arrow-down-right',
  'tabler-arrow-down-right-circle',
  'tabler-arrow-down-square',
  'tabler-arrow-down-tail',
  'tabler-arrow-forward',
  'tabler-arrow-forward-up',
  'tabler-arrow-guide',
  'tabler-arrow-left-bar',
  'tabler-arrow-left-circle',
  'tabler-arrow-left-right',
  'tabler-arrow-left-square',
  'tabler-arrow-left-tail',
  'tabler-arrow-right-bar',
  'tabler-arrow-right-circle',
  'tabler-arrow-right-square',
  'tabler-arrow-right-tail',
  'tabler-arrow-up-bar',
  'tabler-arrow-up-circle',
  'tabler-arrow-up-left',
  'tabler-arrow-up-left-circle',
  'tabler-arrow-up-right',
  'tabler-arrow-up-right-circle',
  'tabler-arrow-up-square',
  'tabler-arrow-up-tail',
  'tabler-arrow-wave-left-down',
  'tabler-arrow-wave-left-up',
  'tabler-arrow-wave-right-down',
  'tabler-arrow-wave-right-up',
  'tabler-arrows-diagonal',
  'tabler-arrows-diagonal-2',
  'tabler-arrows-diagonal-minimize',
  'tabler-arrows-diagonal-minimize-2',
  'tabler-arrows-double-ne-sw',
  'tabler-arrows-double-nw-se',
  'tabler-arrows-double-se-nw',
  'tabler-arrows-double-sw-ne',
  'tabler-arrows-down',
  'tabler-arrows-down-up',
  'tabler-arrows-horizontal',
  'tabler-arrows-join',
  'tabler-arrows-join-2',
  'tabler-arrows-left',
  'tabler-arrows-left-down',
  'tabler-arrows-left-right',
  'tabler-arrows-maximize',
  'tabler-arrows-minimize',
  'tabler-arrows-move',
  'tabler-arrows-move-horizontal',
  'tabler-arrows-move-vertical',
  'tabler-arrows-random',
  'tabler-arrows-right',
  'tabler-arrows-right-down',
  'tabler-arrows-right-left',
  'tabler-arrows-shuffle',
  'tabler-arrows-shuffle-2',
  'tabler-arrows-sort',
  'tabler-arrows-split',
  'tabler-arrows-split-2',
  'tabler-arrows-up',
  'tabler-arrows-up-down',
  'tabler-arrows-up-left',
  'tabler-arrows-up-right',
  'tabler-arrows-vertical',
] as const

