export const tablerIconsPart1 = [
  'tabler-home',
  'tabler-user',
  'tabler-users',
  'tabler-settings',
  'tabler-menu-2',
  'tabler-x',
  'tabler-check',
  'tabler-plus',
  'tabler-minus',
  'tabler-edit',
  'tabler-trash',
  'tabler-search',
  'tabler-filter',
  'tabler-sort-ascending',
  'tabler-sort-descending',
  
  'tabler-arrow-left',
  'tabler-arrow-right',
  'tabler-arrow-up',
  'tabler-arrow-down',
  'tabler-chevron-left',
  'tabler-chevron-right',
  'tabler-chevron-up',
  'tabler-chevron-down',
  'tabler-arrow-back',
  'tabler-arrow-forward',
  
  'tabler-shopping-cart',
  'tabler-shopping-bag',
  'tabler-credit-card',
  'tabler-currency-dollar',
  'tabler-receipt',
  'tabler-tag',
  'tabler-tags',
  
  'tabler-mail',
  'tabler-mail-opened',
  'tabler-phone',
  'tabler-message',
  'tabler-message-circle',
  'tabler-bell',
  'tabler-bell-ringing',
  
  'tabler-file',
  'tabler-file-text',
  'tabler-file-upload',
  'tabler-file-download',
  'tabler-folder',
  'tabler-folder-open',
  'tabler-file-alert',
  'tabler-file-check',
  
  'tabler-calendar',
  'tabler-calendar-event',
  'tabler-clock',
  'tabler-hourglass',
  
  'tabler-alert-circle',
  'tabler-alert-triangle',
  'tabler-info-circle',
  'tabler-check-circle',
  'tabler-x-circle',
  'tabler-help-circle',
  
  'tabler-photo',
  'tabler-camera',
  'tabler-video',
  'tabler-music',
  'tabler-play',
  'tabler-pause',
  
  'tabler-briefcase',
  'tabler-building',
  'tabler-building-store',
  'tabler-chart-bar',
  'tabler-chart-line',
  'tabler-chart-pie',
  'tabler-trending-up',
  'tabler-trending-down',
  
  'tabler-map-pin',
  'tabler-map',
  'tabler-navigation',
  'tabler-plane',
  'tabler-car',
  'tabler-truck',
  
  // User Types (from migration)
  'tabler-clipboard-check', // Inspector
  
  'tabler-download',
  'tabler-upload',
  'tabler-refresh',
  'tabler-reload',
  'tabler-save',
  'tabler-copy',
  'tabler-cut',
  'tabler-clipboard',
  'tabler-link',
  'tabler-external-link',
  
  'tabler-layout',
  'tabler-layout-grid',
  'tabler-layout-list',
  'tabler-columns',
  'tabler-rows',
  'tabler-align-left',
  'tabler-align-center',
  'tabler-align-right',
  'tabler-align-justified',
  
  'tabler-bold',
  'tabler-italic',
  'tabler-underline',
  'tabler-strikethrough',
  'tabler-typography',
  
  'tabler-tool',
  'tabler-wrench',
  'tabler-screwdriver',
  'tabler-hammer',
  'tabler-paint',
  'tabler-color-picker',
  
  'tabler-lock',
  'tabler-lock-open',
  'tabler-shield',
  'tabler-shield-check',
  'tabler-key',
  'tabler-fingerprint',
  
  'tabler-heart',
  'tabler-activity',
  'tabler-pulse',
  'tabler-stethoscope',
  'tabler-pill',
  
  'tabler-school',
  'tabler-book',
  'tabler-bookmark',
  'tabler-certificate',
  'tabler-graduation-cap',
  
  'tabler-device-desktop',
  'tabler-device-mobile',
  'tabler-device-tablet',
  'tabler-wifi',
  'tabler-wifi-off',
  'tabler-bluetooth',
  'tabler-cpu',
  'tabler-server',
  
  'tabler-sun',
  'tabler-moon',
  'tabler-cloud',
  'tabler-cloud-rain',
  'tabler-snowflake',
  'tabler-leaf',
  'tabler-tree',
  
  'tabler-coffee',
  'tabler-glass',
  'tabler-cake',
  'tabler-pizza',
  
  'tabler-ball-football',
  'tabler-ball-basketball',
  'tabler-trophy',
  'tabler-medal',
] as const
