
import type { EntityMetadataType } from '@/constants/entities'
import { GLOBAL_CONFIG_IDS } from '@shared/constants/globalConfigIds'

export type { EntityMetadataType }

export const BLOCK_SHAPE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.BLOCK_SHAPE
export const PART_SHAPE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.PART_SHAPE
export const PART_INSTANCE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.PART_INSTANCE
export const BLOCK_INSTANCE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.BLOCK_INSTANCE
export const EVENT_SHAPE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.EVENT_SHAPE
export const EVENT_INSTANCE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.EVENT_INSTANCE
export const ANNOTATION_SHAPE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.ANNOTATION_SHAPE
export const ANNOTATION_INSTANCE_GLOBAL_CONFIG_ID = GLOBAL_CONFIG_IDS.ANNOTATION_INSTANCE
