import { DEFAULT_MINIMIZER_NO_FEASIBLE_COMPLETION_SLOTS_MESSAGE } from '@/constants/availabilityStepConstants'

export const BUSINESS_CONTROLS_TAB_STRINGS = {
  loading: 'Loading settings...',
  panels: {
    constraints: 'Constraints',
    businessHours: 'Business Hours',
    leadTimeConstraint: 'Lead Time Constraint',
    dateRangeConstraint: 'Date Range Constraint',
    perDayLimit: 'Per Day Limit',
    calendarWeekLimit: 'Calendar Week Limit (Monday-Sunday)',
    rollingWeekLimit: 'Rolling Week Limit (7-day window)',
    incomePerDayLimit: 'Income Per Day Limit',
    incomeCalendarWeekLimit: 'Income Calendar Week Limit',
    incomeRollingWeekLimit: 'Income Rolling Week Limit',
    appointmentBuffers: 'Appointment Buffers',
    driveTimeBuffer: 'Drive Time Buffer',
    driveToCandidateBuffer: 'Drive To Appointment (Arrival)',
    driveFromCandidateBuffer: 'Drive From Appointment (Departure)',
    defaultLocation: 'Default Location',
    lunchBuffer: 'Lunch Buffer',
    outOfOfficeEvents: 'Out-of-Office Events',
    calendar: 'Calendar'
  },
  labels: {
    startTime: 'Start Time',
    endTime: 'End Time',
    minimumLeadTime: 'Minimum Lead Time (minutes)',
    maximumHoursPerDay: 'Maximum Hours Per Day',
    maximumHoursPerWeek: 'Maximum Hours Per Week',
    maximumHours7Days: 'Maximum Hours (7 days)',
    maximumIncomePerDay: 'Maximum Income Per Day ($)',
    maximumIncomePerWeek: 'Maximum Income Per Week ($)',
    maximumIncome7Days: 'Maximum Income (7 days) ($)',
    enforcement: 'Enforcement',
    direction: 'Direction',
    bufferTime: 'Buffer Time (minutes)',
    placement: 'Placement',
    applyTo: 'Apply To',
    timeSlotIncrement: 'Slot Increment',
    timezone: 'Timezone',
    enableDurationRounding: 'Enable Rounding',
    roundingIncrement: 'Rounding Increment (minutes)',
    roundingMethod: 'Rounding Method',
    defaultLocationAddress: 'Home/Office Address',
    defaultLocationLabel: 'Label (optional)'
  },
  validation: {
    startTimeRequired: 'Start time is required',
    endTimeRequired: 'End time is required',
    invalidTimeFormat: 'Invalid time format (HH:MM)',
    leadTimeRequired: 'Lead time is required',
    leadTimeMin: 'Lead time must be 0 or greater',
    mustBeZeroOrGreater: 'Must be 0 or greater',
    cannotExceed24Hours: 'Cannot exceed 24 hours',
    bufferTimeMin: 'Buffer time must be 0 or greater',
    timeIncrementRequired: 'Time increment is required',
    timezoneRequired: 'Timezone is required',
    roundingIncrementRequired: 'Rounding increment is required',
    emailInvalid: 'Please enter a valid email address'
  },
  hints: {
    enforcement: 'Off: No filtering | Flexible: Block if limit already exceeded | Hard: Block if would exceed limit',
    direction: 'How the 7-day window is calculated relative to appointment date',
    bufferTime: 'Time to add around candidate appointments when checking availability',
    placement: 'Where to apply buffer time: Before (before start), After (after end), Both (before and after), Off (no buffer)',
    bufferEnforcement: 'How strictly to enforce buffer: Off (not applied), Flexible (warn), Hard (block)',
    timezone: 'Used for all availability calculations and time slot generation.',
    durationRounding: 'When enabled, appointment durations are rounded to the specified increment using the selected method. Round Up ensures durations never fall short, Round Down prevents exceeding, Round Nearest rounds to closest increment.',
    roundingIncrement: 'Interval to round durations to (e.g., 15 = rounds to nearest 15-minute mark)',
    roundingMethod: 'How to round durations: Round Up (always round up), Round Down (always round down), Round Nearest (round to closest)',
    driveToCandidateMinutes: 'Travel time needed to arrive at candidate appointment',
    driveFromCandidateMinutes: 'Travel time needed to leave from candidate appointment',
    driveTimeApplyTo: 'Which appointments need this buffer',
    defaultLocationAddress: 'Starting point for first appointment, ending point for last',
    defaultLocationLabel: 'Optional label like "Home Office" or "Shop"'
  },
  help: {
    rangeConstraints: 'Range Constraints: Filter slots by when they can occur. Lead time prevents scheduling too close to current time. Date range sets absolute boundaries.',
    enforcement: 'Enforcement: Off = No filtering | Flexible = Block if limit already exceeded | Hard = Block if would exceed limit',
    placement: 'Placement: Off = No buffer | Before = Gap before | After = Gap after | Both = Gaps both sides. Enforcement: Off = Not applied | Flexible = Warn | Hard = Block',
    timeSlots: 'Time slots will be generated at intervals of',
    timezone: 'Business hours and time slots will be interpreted in the selected timezone.',
    currentSelection: 'Current selection:',
    notSet: 'Not set',
    durationRoundingDescription: 'Duration rounding affects how appointment durations are calculated. When disabled, exact durations are used. When enabled, durations are rounded to the specified increment using the selected method.',
    leadTimeDescription: 'Appointments must be scheduled at least',
    leadTimeMinutes: 'minutes in advance',
    leadTimeHours: 'hours',
    leadTimeFilter: 'Lead time filters out slots that are too soon (before current time + lead time minutes)',
    dateRangeNotSetup: 'Not Set-up',
    dateRangeDescription: 'Date range constraints allow you to set absolute start and end boundaries for when appointments can be scheduled.',
    driveTimeNotSetup: 'Not Set-up',
    driveTimeDescription: 'Drive time buffers add travel time between appointments to prevent scheduling conflicts when appointments are at different locations.',
    driveToCandidateDescription: 'Travel time from previous event to candidate appointment. Applied BEFORE the appointment start time.',
    driveFromCandidateDescription: 'Travel time from candidate appointment to next event. Applied AFTER the appointment end time.',
    defaultLocationDescription: 'Your home or office address. Used as the starting point for first appointments and ending point for last appointments.',
    lunchNotSetup: 'Not Set-up',
    lunchDescription: 'Lunch buffers block time for lunch breaks to prevent scheduling appointments during meal times.',
    outOfOfficeDescription: 'Controls whether out-of-office events on your calendar block appointment slots. Events are always fetched for display — this setting controls whether they prevent booking.'
  },
  buttons: {
    saveSettings: 'Save Settings',
    saveOrganizationDefaults: 'Save organization defaults',
    saveRoleAlignment: 'Save role alignment',
    resetToDefaults: 'Reset to Defaults'
  },
  tabs: {
    constraints: 'Constraints',
    calendar: 'Calendar',
    rules: 'Rules',
    mlsMapping: 'MLS Mapping',
    range: 'Range',
    capacity: 'Capacity',
    overlap: 'Overlap',
    integration: 'Integration',
    confirmationAndHolds: 'Holds',
    increment: 'Slot Increment',
    rounding: 'Rounding',
    timezone: 'Timezone',
    places: 'Places',
    grid: 'Grid',
    wizard: 'Wizard',
    organization: 'Organization defaults',
    roleAlignment: 'Role & user-type',
  },
  roleAlignment: {
    cardTitle: 'User role → user-type block instance',
    helpIntro:
      'Maps each canonical user role to at most one user-type block instance (state-control / user shape). When set, this override is used before the older name-based map. Choose one role per instance, then save.',
    instanceLabel: 'User-type instance',
    instanceColumnLabel: 'Instance',
    canonicalRoleColumnLabel: 'Canonical user role',
    /** Outlined select placeholder (mirrors block shape Type field wording). */
    canonicalRoleSelectPlaceholder: 'Select canonical user role',
    mapsToThisInstanceAria: 'This user-type instance is the alignment for this role',
  },
  calendar: {
    integrationTitle: 'Calendar Integration',
    integrationDescription: 'Connect external calendars to check availability and prevent double-booking. Calendar busy periods will be blocked when scheduling appointments.',
    enableLabel: 'Enable Calendar Integration',
    enableHint: 'When enabled, the system will check connected calendars for availability',
    providerLabel: 'Calendar Provider',
    providerHint: 'Select your calendar service provider',
    calendarsTitle: 'Calendars',
    calendarsDescription: 'Configure which calendars to read from (availability) and write to (appointments)',
    addCalendar: 'Add Calendar',
    noCalendars: 'No calendars configured. Click "Add Calendar" to add one.',
    emailLabel: 'Email Address',
    emailHint: 'Calendar email address (e.g., you@example.com)',
    labelOptional: 'Label (Optional)',
    labelHint: 'Friendly name (e.g., Work Calendar)',
    remove: 'Remove',
    readFrom: 'Read From',
    readFromHint: 'Check this calendar for availability',
    writeTo: 'Write To',
    writeToHint: 'Create appointments on this calendar (only one can be selected)',
    writeToOnlyOne: 'Only one calendar can be selected for writing',
    authRequired: 'Authentication Required:',
    authAfterSave: 'After saving, you\'ll need to authenticate with',
    authToAllow: 'to allow the system to access your calendar data.',
    authPrivacy: 'Calendar data is only used to check availability. No events will be modified without your permission.',
    disabledHint: 'Calendar integration is currently disabled. Enable it above to configure calendar connections.',
    appointmentHoldsTitle: 'Appointment Holds',
    holdDurationLabel: 'Default Hold Duration (minutes)',
    holdDurationHint: 'How long a slot is held before it expires when a user holds a time slot. Between 1 and 60 minutes.',
    holdDurationMin: 'Hold duration must be at least 1 minute',
    holdDurationMax: 'Hold duration cannot exceed 60 minutes',
    autoConfirmLabel: 'Auto-confirm appointments',
    autoConfirmHint: 'When enabled, new appointments created with status "Submitted" are automatically transitioned to "Confirmed".',
    showApplyCouponLabel: 'Show apply coupon in wizard',
    showApplyCouponHint: 'When on, the Coupon Discount row and Apply Coupon button are visible in the booking summary and fee preview.',
    useBrandColorsLabel: 'Brand colors',
    useBrandColorsHint: 'When on, the booking wizard uses DHP brand colors (safety yellow / day-glow red) instead of the default theme.',
    adminEntryTimeoutLabel: 'Admin entry dropdown time-out',
    adminEntryTimeoutHint: 'Only show appointments in the Edit quote / Reschedule dropdown where scheduling began within the last X days or weeks (or quote in quote status for last X). Used to limit the list to recent inspections.',
    driveTimeFeeSectionTitle: 'Drive time fees (billing)',
    driveTimeFeeSectionHint:
      'Billing for drive time is separate from drive buffers under Constraints → Overlap. These values persist with availability settings and are available to the booking client when settings load.',
    complimentaryDriveMinutesLabel: 'Complimentary drive time (minutes)',
    complimentaryDriveMinutesHint: 'Drive minutes included at no charge before the hourly rate applies.',
    drivingRatePerHourLabel: 'Driving rate ($ / hour)',
    drivingRatePerHourHint: 'Dollar amount per hour for billable drive time after complimentary minutes.',
    driveTimeRoundingMinutesLabel: 'Billable drive rounding (minutes)',
    driveTimeRoundingMinutesHint: 'Billable drive time is rounded up to this increment. Must be at least 1 minute.'
  },
  brand: {
    sectionTitle: 'Brand customization',
    sectionHint:
      'Logo and anchor colors for the booking wizard when Brand colors is enabled. Click Save settings to persist.',
    currentLogoAlt: 'Current wizard logo',
    logoLabel: 'Logo file',
    logoHint: 'PNG or JPEG. Choose a file, then upload or extract colors.',
    uploadButton: 'Upload logo',
    extractButton: 'Extract colors from image',
    modeDeltasTitle: 'Quote & reschedule palette shifts',
    modeDeltasHint:
      'OKLCH tweaks for quote (clockwise hue) and reschedule (counter-clockwise). Percent of full color wheel; chroma multipliers vs anchors. Save settings to apply in the booking wizard.',
    quoteHuePercentLabel: 'Quote hue (% of color wheel)',
    quoteHuePercentHint: 'Clockwise rotation. 20 = one-fifth of the circle (default).',
    quoteChromaLabel: 'Quote chroma multiplier',
    quoteChromaHint: 'Below 1 = less saturated; default 0.8.',
    rescheduleHuePercentLabel: 'Reschedule hue (% of color wheel)',
    rescheduleHuePercentHint: 'Counter-clockwise rotation magnitude. Default 20.',
    rescheduleChromaLabel: 'Reschedule chroma multiplier',
    rescheduleChromaHint: 'Above 1 = more saturated; default 1.2.',
    warningAdjustersTitle: 'Warning color (vs secondary)',
    warningAdjustersHint:
      'Applied after quote/reschedule mode on the secondary-derived color. Hue is clockwise; default 0% and 1× keeps warning equal to secondary.',
    warningHuePercentLabel: 'Warning hue (% of color wheel)',
    warningHuePercentHint: 'Extra rotation on top of mode-adjusted secondary. 0 = match secondary.',
    warningChromaLabel: 'Warning chroma multiplier',
    warningChromaHint: 'Relative to mode-adjusted secondary. Default 1.',
    primaryHexLabel: 'Primary anchor (hex)',
    primaryHexHint: 'Six-digit hex (e.g. #EED202). Drives the yellow family in OKLCH-derived palettes.',
    secondaryHexLabel: 'Secondary anchor (hex)',
    secondaryHexHint: 'Six-digit hex (e.g. #FF3333). Drives the red family.',
    previewTitle: 'Preview (standard mode)',
    previewPrimary: 'Primary',
    previewSecondary: 'Secondary',
    previewWarning: 'Warning',
    uploadFailed: 'Upload failed. Check the file and try again.',
    extractFailed: 'Could not read colors from this image. Try another file.'
  },
  driveTime: {
    calculatedTitle: 'Calculated Drive Times',
    calculatedCaption: 'Drive times will be calculated using Google Maps Routes API based on your default location and appointment addresses.',
    estimatedTitle: 'Estimated Drive Times',
    estimatedCaption: 'Drive times will use the static value below. Set a default location with a valid address to enable calculated drive times.',
    calculatedRoutesTitle: 'Calculated Drive Times (Routes API Active)',
    calculatedRoutesCaption: 'Drive times are calculated using Google Maps Routes API based on your default location and appointment addresses. The value below is used as a backup if the API is unavailable or returns no route.',
    staticTitle: 'Static Drive Times (Static Only)',
    staticCaption: 'Drive times will use the static value below. Set a default location with a valid address to enable calculated drive times from Google Maps Routes API.',
    minutesLabel: 'Minutes',
    backupMinutesLabel: 'Backup Minutes',
    backupHint: 'Used if Routes API fails or returns no route'
  },
  differential: {
    sectionTitle: 'Differential Perspectives',
    sectionDescription: 'Configure attendee quick-select presets and customize perspective display labels. Event types control timing; event instance attendees control who is invited.',
    majorAttendeesLabel: 'Internal Attendee Preset',
    majorAttendeesHint: 'UserTypeBlock instances commonly used for internal/full-window segments (e.g., Inspector)',
    majorLabelLabel: 'Major Label',
    majorLabelHint: 'Display label for major perspective (e.g., Major)',
    minorAttendeesLabel: 'Client-Facing Attendee Preset',
    minorAttendeesHint: 'UserTypeBlock instances commonly used for client-facing segments (e.g., Client)',
    minorLabelLabel: 'Minor Label',
    minorLabelHint: 'Display label for minor perspective (e.g., Minor Formal Presentation)',
    minimizerFallbackLabel: 'Minimizer label (when shape unknown)',
    minimizerFallbackHint: 'Used when a minimizer part-shape name cannot be determined (e.g., Post-Appointment Work)',
    graphDefaultLabel: 'Differential Graph Default Label',
    graphDefaultHint: 'Message shown when no time slot is selected (e.g., Select a Time Slot)',
    majorStateLabel: 'Major State Label',
    majorStateHint: 'Message shown when major perspective is selected (e.g., Showing Major Times). Leave empty to use default format.',
    minorStateLabel: 'Minor State Label',
    minorStateHint: 'Message shown when minor perspective is selected (e.g., Showing Client FormalPresentation Times). Leave empty to use default format.',
    helpMajor: 'Internal Attendee Preset: convenience set for segment attendee selectors.',
    helpMinor: 'Client-Facing Attendee Preset: convenience set for segment attendee selectors.',
    helpLabels: 'Labels: Customize how major and minor perspectives are displayed in the UI.',
    helpMinimizerFallback:
      'Minimizer label (when shape unknown): Used when no minimizer part-shape can be resolved from event assignments.',
    helpGraphDefault: 'Differential Graph Default Label: Shown over the graph when no time slot is selected, and as the Perspective card title in the accordion.',
    subStepLabelsSectionTitle: 'Availability Sub-Step Card Titles',
    subStepLabelsSectionHint: 'Titles for collapsed availability cards in the accordion. Perspective card uses "Differential Graph Default Label" above.',
    subStepLabelPickDay: 'Pick a Day',
    subStepLabelPickDayHint: 'Card title for date selection (e.g., Pick a day)',
    subStepLabelOptions: 'Options',
    subStepLabelOptionsHint: 'Card title for availability options (e.g., Options)',
    subStepLabelPickTime: 'Pick a Time',
    subStepLabelPickTimeHint: 'Card title for time slot selection (e.g., Pick a time)',
    subStepLabelConfirmMinimizer: 'Confirm Minimizer Details',
    subStepLabelConfirmMinimizerHint: 'Card title for minimizer confirmation (e.g., Confirm minimizer details)',
    minimizerNoFeasibleCompletionSlotsMessage: 'No Feasible Minimizer Slots Message',
    minimizerNoFeasibleCompletionSlotsMessageHint:
      'Shown in booking when the customer chooses a contingency deadline but no completion times fit. Leave empty to use the default text.',
    helpStateLabels: 'State Labels: Messages shown when a time slot is selected. If left empty, defaults to "Showing {Major/Minor Label} times".',
    helpFallback: 'If not configured, the system falls back to hardcoded "Major" (major) and "Minor" (minor) event names, and default labels.'
  },
  placeholders: {
    emailAddress: 'Enter email address',
    workCalendar: 'e.g., Work Calendar',
    homeOffice: 'Home Office',
    addressTyping: 'Start typing your address...'
  },
  defaults: {
    majorLabel: 'Inspector',
    minorLabel: 'Minor Formal Presentation',
    minimizerFallbackLabel: 'Post-Appointment Work',
    differentialGraphDefaultLabel: 'Select a Time Slot',
    subStepLabelPickDay: 'Pick a day',
    subStepLabelOptions: 'Options',
    subStepLabelPickTime: 'Pick a time',
    subStepLabelConfirmMinimizer: 'Confirm minimizer details',
    minimizerNoFeasibleCompletionSlotsMessage: DEFAULT_MINIMIZER_NO_FEASIBLE_COMPLETION_SLOTS_MESSAGE,
  },
  orgDefaultBadges: {
    orgDefault: 'Org default',
    override: 'Override',
  },
  sections: {
    durationRoundingTitle: 'Rounding',
    defaultLocationTitle: 'Default Location',
    timezoneSettingsTitle: 'Timezone Settings',
    gridConfigTitle: 'Grid Configuration',
    slotIncrementTitle: 'Slot Increment',
    coordinatesLabel: 'Coordinates:',
    placeIdLabel: 'Place ID:'
  }
} as const
