/**
 * Lint Audit Script
 *
 * Runs ESLint (client only), captures all messages (errors + warnings),
 * applies inline and config allowlist exceptions, scores per file, and
 * outputs deterministic JSON + Markdown with P0/P1/P2 priority.
 *
 * Output: .audit-reports/lint-audit.json, .audit-reports/lint-audit.md
 * Each finding includes severity (1 = warning, 2 = error) for downstream lint-warnings audit.
 */

import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import {
  getAuditReportHeaderLines,
  isGloballyExcluded,
  loadCentralAllowlist,
  resolveAuditPaths,
  writeAuditReports,
  toRepoPath as toRepoPathUtil,
  parseInlineExceptions,
  isMatchAllowed,
} from './shared-audit-utils.mjs'

const AUDIT_TYPE = 'lint'

const DEFAULT_RULE_WEIGHTS = {
  'vue/no-mutating-props': 4,
  '@typescript-eslint/no-explicit-any': 3,
  '@typescript-eslint/no-unused-vars': 2,
}

function toRepoPath(filePath, projectRoot, clientRoot) {
  const resolved = path.isAbsolute(filePath)
    ? filePath
    : path.join(clientRoot, filePath)
  return toRepoPathUtil(resolved, projectRoot)
}

function assignPriority(score, config) {
  const p0Min = Number(config?.priorities?.p0MinSeverityScore ?? 15)
  const p1Min = Number(config?.priorities?.p1MinSeverityScore ?? 6)
  if (score >= p0Min) return 'P0'
  if (score >= p1Min) return 'P1'
  return 'P2'
}

function runEslint(clientRoot) {
  const result = spawnSync('npx', ['eslint', '.', '--format', 'json'], {
    cwd: clientRoot,
    encoding: 'utf-8',
    maxBuffer: 10 * 1024 * 1024,
  })
  return { stdout: result.stdout || '', stderr: result.stderr || '', status: result.status }
}

function getFileContent(absPath) {
  try {
    return fs.readFileSync(absPath, 'utf8')
  } catch {
    return ''
  }
}

const inlineExceptionCache = new Map()

function getInlineExceptions(repoPath, projectRoot) {
  if (inlineExceptionCache.has(repoPath)) {
    return inlineExceptionCache.get(repoPath)
  }
  const absPath = path.join(projectRoot, repoPath)
  const content = getFileContent(absPath)
  const exceptions = parseInlineExceptions(content, AUDIT_TYPE)
  inlineExceptionCache.set(repoPath, exceptions)
  return exceptions
}

function renderMarkdownReport(result) {
  const lines = []
  lines.push(...getAuditReportHeaderLines())
  lines.push('# Lint Audit (Generated)')
  lines.push('')
  lines.push('Generated by `client/.scripts/lint-audit.mjs`.')
  lines.push('')
  lines.push('## Summary')
  lines.push('')
  lines.push(`- Files with findings: **${result.files.length}**`)
  lines.push(`- Total findings: **${result.findings.length}**`)
  lines.push('')

  const byRule = {}
  for (const f of result.findings) {
    byRule[f.ruleId] = (byRule[f.ruleId] || 0) + 1
  }
  lines.push('| Rule | Count |')
  lines.push('| --- | ---: |')
  for (const [ruleId, count] of Object.entries(byRule).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${ruleId} | ${count} |`)
  }
  lines.push('')

  if (result.files.length > 0) {
    lines.push('## Files by Severity')
    lines.push('')
    lines.push('| File | Priority | Score |')
    lines.push('| --- | --- | ---: |')
    for (const f of result.files.slice(0, 40)) {
      lines.push(`| \`${f.file}\` | ${f.priority} | ${f.score} |`)
    }
    if (result.files.length > 40) {
      lines.push(`| *...and ${result.files.length - 40} more* | | |`)
    }
    lines.push('')
  }

  const byRuleList = Object.entries(byRule).sort((a, b) => b[1] - a[1]).slice(0, 15)
  for (const [ruleId] of byRuleList) {
    const ruleFindings = result.findings.filter((f) => f.ruleId === ruleId)
    if (ruleFindings.length === 0) continue
    lines.push(`## ${ruleId}`)
    lines.push('')
    lines.push('| File | Line | Message |')
    lines.push('| --- | ---: | --- |')
    for (const f of ruleFindings.slice(0, 25)) {
      const msg = (f.message || '').replace(/\|/g, '\\|').slice(0, 60)
      lines.push(`| \`${f.file}\` | ${f.lineNumber} | ${msg} |`)
    }
    if (ruleFindings.length > 25) {
      lines.push(`| *...and ${ruleFindings.length - 25} more* | | |`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

function main() {
  const paths = resolveAuditPaths(AUDIT_TYPE)

  let config = {}
  try {
    if (fs.existsSync(paths.configPath)) {
      config = JSON.parse(fs.readFileSync(paths.configPath, 'utf8'))
    }
  } catch {
    /* defaults */
  }

  const configAllowlist = loadCentralAllowlist(AUDIT_TYPE)
  const ruleWeights = { ...DEFAULT_RULE_WEIGHTS, ...(config.ruleWeights || {}) }

  const { stdout, status } = runEslint(paths.clientRoot)

  let rawResults = []
  try {
    rawResults = JSON.parse(stdout.trim() || '[]')
  } catch (e) {
    console.error('Failed to parse ESLint JSON output:', e.message)
    process.exitCode = 1
    return
  }

  const allFindings = []
  const fileScores = new Map()
  let totalScanned = 0

  for (const fileResult of rawResults) {
    const filePathRaw = fileResult.filePath || ''
    const repoPath = toRepoPath(filePathRaw, paths.projectRoot, paths.clientRoot)
    if (isGloballyExcluded(repoPath)) continue
    totalScanned += 1

    const inlineExceptions = getInlineExceptions(repoPath, paths.projectRoot)

    for (const msg of fileResult.messages || []) {
      const ruleId = msg.ruleId || 'unknown'
      const line = msg.line || 0
      const allowed = isMatchAllowed(repoPath, ruleId, line, inlineExceptions, configAllowlist)
      if (allowed.allowed) continue

      const severity = msg.severity === 2 ? 2 : 1
      const weight = ruleWeights[ruleId] ?? (severity === 2 ? 3 : 1)

      allFindings.push({
        file: repoPath,
        repoPath,
        lineNumber: line,
        ruleId,
        severity,
        message: msg.message || '',
        source: msg.source ? String(msg.source).slice(0, 80) : undefined,
      })

      const prev = fileScores.get(repoPath) || 0
      fileScores.set(repoPath, prev + weight)
    }
  }

  const files = Array.from(fileScores.entries())
    .map(([file, score]) => ({
      file,
      repoPath: file,
      score,
      priority: assignPriority(score, config),
    }))
    .sort((a, b) => b.score - a.score)

  const result = {
    generatedAt: new Date().toISOString(),
    totalScanned,
    findings: allFindings,
    files,
  }

  const { outJson, outMd } = writeAuditReports(AUDIT_TYPE, result, renderMarkdownReport(result))

  console.log(`Wrote:\n- ${outJson}\n- ${outMd}`)
  console.log(`Findings: ${allFindings.length} (files with findings: ${files.length})`)
  // WHY: Do not propagate ESLint's exit code (status). The audit succeeds if it ran and wrote
  // the report. Finding counts and file lists are in the report for CI/summaries; exiting 1
  // here would break audit:all and downstream summaries without adding information.
}

main()
